
const COURSE_ENROLLMENT = 10;
const LESSON_COMPLETION = 30;
const COURSE_COMPLETION = 150;
const SUBMIT_QUIZ = 10;



module.exports = {
  LESSON_COMPLETION,
  COURSE_ENROLLMENT,
  COURSE_COMPLETION,
  SUBMIT_QUIZ,
};